### ISSUE TITLE
Stylesheet has an incorrect reference to font-awesome

### ISSUE THREAD

**Issue by ronaldsankey** [PredixDev/px-modal#14]
Css/px-modal-styles references '../font-awesome.......' which doesn't exist.  I am assuming it is meant to be a dependency and then it should be ../../font-awesome.

**Comment by randyaskin** [comment]
Every one of our components imports px-iconography-design (via px-buttons-design via px-starter-kit-design), which is where this particular line of code is coming from, and we've never seen any problems with it. As you can see, once you run `gulp serve` the /css folder and /font-awesome folders are peers. I've tested on `polymer serve` as well, no errors. Are you actually seeing any errors in your console due to this?

![screen shot 2017-03-02 at 12 05 43 pm](https://cloud.githubusercontent.com/assets/2130613/23524962/a82dddf0-ff41-11e6-8059-7f5353cf539a.png)

**Comment by ronaldsankey** [comment]
I can post a screenshot tomorrow, I think this works for you because of the gulp processing.  It has the two directories at the same level.  I am using components within Angular and Webpack keeps the structure.  They are not at the same level.  Looking at network calls, it gets 404 errors during deployment. I also see errors during 'Ng test --single run'

**Comment by ronaldsankey** [comment]
Just yesterday I ran across a similar issue where setting up my scss files imports within an angular2 app, it cannot resolve all of the dependencies due to how all of the px- components are written.  I have to actually preprocess all px scss style sheets to get a temporary 'main.css'. file which is then included in the Angular2 app.   I wish I didn't have to do that step.

**Comment by mdwragg** [comment]
Hi, I'd love to get to the bottom of this but can't recreate it. Can you please create a test-repo that we can clone, run and recreate the issue in? Thanks for your help.

**Comment by randyaskin** [comment]
I believe this was resolved. See https://github.com/PredixDev/px-data-table/issues/93
